# Current feeling and reason
# Plans for the day

personas_qa = {
  1:{"question_no": 1, "qtype": "system_qa", "question": "What is your full name?", "answer": ""},
  2:{"question_no": 2, "qtype": "system_qa", "question": "Do you want to set name for your agent? If yes, what is the name of your agent?", "answer": ""},
  3:{"question_no": 3, "qtype": "system_qa", "question": "How would you prefer the agent to communicate with others (Formal, Casual, Friendly, Humorous, Motivational, Empathetic, Direct and Concise, Detailed and Informative, Neutral/Professional, Cheerful/Optimistic)?", "answer": ""},
  4:{"question_no": 4, "qtype": "system_qa", "question": "Do you prefer concise answers or detailed explanations?", "answer": ""},
  5:{"question_no": 5, "qtype": "system_qa", "question": "How do you want the agent to behave overall (Funny, Serious, Empathetic, Motivational, Supportive, Casual, Professional, Inquisitive, Encouraging, Laid-back)?", "answer": ""},
  6:{"question_no": 6, "qtype": "system_qa", "question": "What type of humor do you prefer (Sarcastic, Light, Witty, No Humor at All, Dry Humor, Playful, Self-deprecating, Slapstick, Punny, Cynical)?", "answer": ""},
  7:{"question_no": 7, "qtype": "system_qa", "question": "What is your profession and what do you do for living?", "answer": ""},
  8:{"question_no": 8, "qtype": "system_qa", "question": "How old are you and What is your birthday YYYY-MM-DD?", "answer": ""},
  9:{"question_no": 9, "qtype": "system_qa", "question": "Where do you live (city, country)?", "answer": ""},
  10:{"question_no": 10, "qtype": "bg_qa", "question": "Can you describe a typical day for you, including details like your work hours, exercise routine, hobbies, meal times, commute, family time, social activities, relaxation or leisure time, personal development activities (e.g., reading, learning new skills), and your sleep schedule?", "answer": ""},
  11:{"question_no": 11, "qtype": "bg_qa", "question": "What is your current occupation or role (e.g., student, professional, freelancer, entrepreneur, stay-at-home parent, retiree)?", "answer": ""},
  12:{"question_no": 12, "qtype": "bg_qa", "question": "What time do you usually wake up and go to sleep?", "answer": ""},
  13:{"question_no": 13, "qtype": "bg_qa", "question": "What’s a challenge or pain point you frequently face in your daily routine?", "answer": ""},
  14:{"question_no": 14, "qtype": "bg_qa", "question": "What short-term goals are you currently working on (e.g., Fitness, Learning, Career Advancement, Health and Wellness, Personal Finance Management, Skill Development (e.g., coding, design), Time Management, Building New Habits, Networking, Creative Projects (e.g., writing, art, music)?", "answer": ""},
  15:{"question_no": 15, "qtype": "bg_qa", "question": "What long-term goals do you have (e.g., Career Advancement, Personal Development, Financial Independence, Higher Education (e.g., obtaining a degree), Homeownership, Retirement Planning, Building a Business, Travel Goals (e.g., visiting specific countries or locations), Family Planning, Community Involvement or Volunteering)?", "answer": ""},
  16:{"question_no": 16, "qtype": "bg_qa", "question": "What are your hobbies or favorite activities?", "answer": ""},
  17:{"question_no": 17, "qtype": "bg_qa", "question": "What kind of content do you enjoy (e.g., Books, Movies, Music, Podcasts, TV Shows, Documentaries, Online Courses, Articles or Blogs, Social Media Content (e.g., TikTok, Instagram), Video Games)?", "answer": ""},
  18:{"question_no": 18, "qtype": "bg_qa", "question": "What are your favorite travel destinations or places you want to visit?", "answer": ""},
  19:{"question_no": 19, "qtype": "bg_qa", "question": "What topics do you enjoy discussing (e.g., Tech, Sports, Health, Art, Travel, Food and Cooking, History, Science, Personal Development, Politics)?", "answer": ""},
  20:{"question_no": 20, "qtype": "bg_qa", "question": "How would you describe your personality (e.g., Outgoing, Introverted, Analytical, Creative, Empathetic, Pragmatic, Adventurous, Detail-oriented, Optimistic, Cautious)?", "answer": ""},
  21:{"question_no": 21, "qtype": "bg_qa", "question": "How do you usually feel when you start your day (e.g., Energized, Stressed, Neutral, Motivated, Anxious, Focused, Tired, Optimistic, Overwhelmed, Relaxed)?", "answer": ""},
  22:{"question_no": 22, "qtype": "bg_qa", "question": "How do you prefer to receive feedback or advice (e.g., Direct, Gentle, Detailed, Constructive, Positive Reinforcement, Supportive, Honest and Straightforward, Empathetic, Informal, Actionable Steps)?", "answer": ""},
  23:{"question_no": 23, "qtype": "bg_qa", "question": "Do you have any dietary preferences or restrictions?", "answer": ""},
  24:{"question_no": 24, "qtype": "bg_qa", "question": "How do you usually relax or unwind after a busy day?", "answer": ""},
  25:{"question_no": 25, "qtype": "bg_qa", "question": "What kind of exercise or physical activities do you enjoy, if any?", "answer": ""},
  26:{"question_no": 26, "qtype": "bg_qa", "question": "What languages do you speak fluently?", "answer": ""},
  27:{"question_no": 27, "qtype": "bg_qa", "question": "What’s your educational background or area of expertise?", "answer": ""},
  28:{"question_no": 28, "qtype": "bg_qa", "question": "Do you live with family, roommates, or by yourself?", "answer": ""},
  29:{"question_no": 29, "qtype": "bg_qa", "question": "What is your preferred time zone for scheduling tasks or appointments?", "answer": ""},
  30:{"question_no": 30, "qtype": "bg_qa", "question": "Do you have any specific morning routines or habits you follow?", "answer": ""},
  31:{"question_no": 31, "qtype": "bg_qa", "question": "How do you typically spend your weekends or days off?", "answer": ""},
  32:{"question_no": 32, "qtype": "bg_qa", "question": "What type of events or activities do you enjoy attending (e.g., Concerts, Sports Events, Art Exhibitions, Theater Performances, Festivals, Workshops or Classes, Conventions or Trade Shows, Movie Screenings, Food and Wine Tastings, Community Events or Fairs)?", "answer": ""},
  33:{"question_no": 33, "qtype": "bg_qa", "question": "Do you prefer spontaneous plans or structured schedules?", "answer": ""},
  34:{"question_no": 34, "qtype": "bg_qa", "question": "Which social causes or topics are you passionate about?", "answer": ""},
  35:{"question_no": 35, "qtype": "bg_qa", "question": "How do you typically handle stress or challenging situations?", "answer": ""},
  36:{"question_no": 36, "qtype": "bg_qa", "question": "When faced with a difficult decision, how do you usually approach it (impulse vs. thoughtful consideration)?", "answer": ""},
  37:{"question_no": 37, "qtype": "bg_qa", "question": "Do you prefer setting small, achievable goals or ambitious, long-term challenges?", "answer": ""},
  38:{"question_no": 38, "qtype": "bg_qa", "question": "How do you motivate yourself to achieve long-term goals?", "answer": ""},
  39:{"question_no": 39, "qtype": "bg_qa", "question": "What’s your approach to problem-solving: logical and analytical, or intuitive and emotional?", "answer": ""},
  40:{"question_no": 40, "qtype": "bg_qa", "question": "How do you handle situations where you're unsure of the outcome (take risks or proceed cautiously)?", "answer": ""},
  41:{"question_no": 41, "qtype": "bg_qa", "question": "Do you prefer structure and routine, or do you thrive in flexibility and spontaneity?", "answer": ""},
  42:{"question_no": 42, "qtype": "bg_qa", "question": "How do you define success for yourself (external achievements vs. internal fulfillment)?", "answer": ""},
  43:{"question_no": 43, "qtype": "bg_qa", "question": "What are your biggest fears or concerns when facing new challenges?", "answer": ""},
  44:{"question_no": 44, "qtype": "bg_qa", "question": "Do you find it easy to focus for long periods, or do you get distracted easily?", "answer": ""},
  45:{"question_no": 45, "qtype": "bg_qa", "question": "How do you manage mental fatigue or burnout?", "answer": ""},
  46:{"question_no": 46, "qtype": "bg_qa", "question": "How important is it for you to feel in control of situations in your life?", "answer": ""},
  47:{"question_no": 47, "qtype": "bg_qa", "question": "When learning something new, do you prefer to experiment and learn from mistakes, or follow a proven path?", "answer": ""}
}
